# GitHub Action para gerar a animação da cobrinha de contribuições

name: Generate snake animation

on:
  schedule:
    # Roda a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Adicione este bloco de permissão
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: matheuscbs
          # O caminho de saída agora é 'dist', que é o padrão da action de commit
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        # A action de commit simplifica o processo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update snake animation"
          file_pattern: dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
